### ISSUE TITLE
服务端提供跟踪记录涉及的所有用户信息，并可以根据用户信息做筛选

### ISSUE THREAD

**Issue by woohling** [ezbim/webBIM#54]
3) 分页之后，服务端提供所有材料跟踪中用户的信息；（筛选的时候只能筛选最新一条材料跟踪的跟踪人，是否合理？）

**Comment by woohling** [comment]
Closed Issues:
1）fancyBox 显示多张图片时，视图显示优化；

**Comment by godion** [comment]
see  #82
